# Generated by Django 4.2 on 2024-01-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="journal",
            old_name="creationDate",
            new_name="creation_date",
        ),
        migrations.RenameField(
            model_name="volume",
            old_name="releaseDate",
            new_name="release_date",
        ),
        migrations.RemoveField(
            model_name="volume",
            name="img",
        ),
        migrations.AddField(
            model_name="journal",
            name="chief_editor",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="journal",
            name="director_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="journal",
            name="slogan",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="volume",
            name="cover_img",
            field=models.ImageField(
                blank=True, null=True, upload_to="volume_cover_images/"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="department_name",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Select a major"),
                    ("CE", "Computer Engineering"),
                    ("CS", "Computer Science"),
                    ("CVE", "Civil Engineering"),
                    ("EE", "Electrical Engineering"),
                    ("ME", "Mechanical Engineering"),
                    ("CME", "Chemical Engineering"),
                    ("AE", "Aerospace Engineering"),
                    ("PHY", "Physics"),
                    ("MATH", "Mathematics"),
                    ("CHEM", "Chemistry"),
                ],
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="journal_logos/"),
        ),
        migrations.AlterField(
            model_name="volume",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
