# Generated by Django 4.2 on 2024-02-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_rename_creationdate_journal_creation_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journal",
            options={"permissions": []},
        ),
        migrations.AlterModelOptions(
            name="volume",
            options={"permissions": []},
        ),
        migrations.RemoveField(
            model_name="journal",
            name="id",
        ),
        migrations.AlterField(
            model_name="journal",
            name="name",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="volume",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="journal",
            table="Journal",
        ),
        migrations.AlterModelTable(
            name="volume",
            table="Volume",
        ),
    ]
