version: "3.9"

services:
  server:
    build:
      context: ./sourceCode
      dockerfile: Dockerfile.prod
    command: gunicorn Sharif_Pub_Server.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/serverCode
    networks:
      - mynetwork
    ports:
      - "8000:8000"
    env_file:
      - ./.productionEnv
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - mynetwork
    env_file:
      - ./.productionEnvDb

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - server

volumes:
  postgres_data:
  static_volume:

networks:
  mynetwork:
    driver: bridge  # custom bridge network "mynetwork", and web and db are connected to this network



# Create a new Django project inside the Docker container: docker compose run web django-admin startproject Sharif_Pub_Server /serverCode
# Build and run the Docker containers: docker compose build
# Run Docker containers: docker compose up -d
# for see logs: docker compose logs web