# Generated by Django 4.2 on 2024-02-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publisher",
            options={"permissions": []},
        ),
        migrations.AlterModelOptions(
            name="reader",
            options={"permissions": []},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="id",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="publisher",
            table="Publisher",
        ),
        migrations.AlterModelTable(
            name="reader",
            table="Reader",
        ),
    ]
