# Generated by Django 4.2 on 2024-02-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial"),
        ("user", "0002_customuser_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publisher",
            options={
                "permissions": [
                    ("can_read", "Can read volumes"),
                    ("can_publish", "Can publish volumes"),
                    ("can_delete", "Can delete volumes"),
                    ("can_edit", "Can edit volumes"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="reader",
            options={
                "permissions": [
                    ("can_read", "Can read volumes"),
                    ("can_like", "Can like volumes"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="reader",
            name="liked_volumes",
            field=models.ManyToManyField(null=True, to="journal.volume"),
        ),
        migrations.AlterModelTable(
            name="publisher",
            table="Publisher",
        ),
        migrations.AlterModelTable(
            name="reader",
            table="Reader",
        ),
    ]
