# Generated by Django 4.2 on 2024-02-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial"),
        ("user", "0003_alter_publisher_options_alter_reader_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reader",
            name="comments",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="reader",
            name="liked_volumes",
            field=models.ManyToManyField(blank=True, to="journal.volume"),
        ),
    ]
